const competitions = [
  {
    id: 1,
    name: "NextGen Enterprise 2.0",
    description: "A business development program equipping MSMEs and entrepreneurs in agriculture, tourism, services, and FMCG sectors with skills to strengthen and grow their enterprises.",
    category: "Business",
    level: "University",
    deadline: "2026-08-14",
    status: "Open",
    image: "assets/images/image_1.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 2,
    name: "Clean Energy Awards 2026",
    description: "An award recognizing businesses, innovations, and initiatives driving Cambodia's clean energy transition, across the Clean Energy Champion, Energy Efficiency, and Cleantech Award categories.",
    category: "Environment",
    level: "Open to All",
    deadline: "2026-08-22",
    status: "Open",
    image: "assets/images/image_2.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 3,
    name: "KE Startup Awards 2026",
    description: "Khmer Enterprise's annual awards competition recognizing outstanding Cambodian startups, entrepreneurs, and SMEs for their innovative contributions to the country's entrepreneurial ecosystem.",
    category: "Business",
    level: "University",
    deadline: "2026-07-15",
    status: "Closed",
    image: "assets/images/image_3.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 4,
    name: "RISE Week 2026",
    description: "A capstone event celebrating young innovators from Tech for Kids Academy's flagship programs, featuring project showcases, a team pitching competition, industry talks, and an award ceremony.",
    category: "Tech",
    level: "High School",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_4.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 5,
    name: "Reverse Innovation Cohort 6",
    description: "A 3-month accelerator program for startups to develop tech-based solutions to real market challenges presented by industry Challenge Owners, with mentorship from domain experts.",
    category: "Tech",
    level: "University",
    deadline: "2026-07-23",
    status: "Closed",
    image: "assets/images/image_5.jpg",
    registerLink: "https://airtable.com/appz0Cfn1uXVH.../pagMFJrW9MjkttSBQ/form",
    featured: true
  },
  {
    id: 6,
    name: "ASEAN Youth Speech Contest 2026",
    description: "A public speaking competition inviting ASEAN youth aged 16-25 to share their vision on the theme 'Navigating Our Future, Together.'",
    category: "Non-Tech",
    level: "University",
    deadline: "2026-07-03",
    status: "Closed",
    image: "assets/images/image_6.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 7,
    name: "Creator Marathon Open Competition",
    description: "An open content creation competition under the Mekong Tech Festival's 4th GenZ Mekong Tech 2026 event, themed Build, Compete, Connect, Scale.",
    category: "Design",
    level: "Open to All",
    deadline: "2026-09-25",
    status: "Open",
    image: "assets/images/image_7.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 8,
    name: "Highschool Club Entrepreneurs Program 2026",
    description: "A program by Khmer Enterprise for high school students to join an entrepreneurship club, building foundational business and startup skills.",
    category: "Business",
    level: "High School",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_8.jpg",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 9,
    name: "Bridging the Cold Chain Gap Challenge",
    description: "A technology innovation challenge by ADB and the High-Level Technology Fund seeking affordable cold chain solutions to reduce post-harvest food loss for last-mile fruit and vegetable vendors in India.",
    category: "Tech",
    level: "Open to All",
    deadline: "2026-09-04",
    status: "Open",
    image: "assets/images/image_9.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 10,
    name: "Turing Hackathon Cycle 10",
    description: "A five-day, community-driven hackathon empowering youth to build digital solutions that drive innovation and cultivate entrepreneurship for Cambodia's next generation of founders. Held in Siem Reap this cycle.",
    category: "Tech",
    level: "University",
    deadline: "2026-06-14",
    status: "Closed",
    image: "assets/images/image_10.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 11,
    name: "FrancoTech Innovation Competition 2026",
    description: "An international competition organized by Cambodia's Ministry of Post and Telecommunications, held alongside the 20th Francophonie Summit in Phnom Penh, recognizing breakthrough digital innovations across Francophone nations. Categories include Best Digital Innovation and Best Women Technopreneurs, open to startups, innovators, entrepreneurs, and digital solution providers from Francophone countries.",
    category: "Tech",
    level: "Open to All",
    deadline: "2026-09-01",
    status: "Open",
    image: "assets/images/image_11.jpg",
    registerLink: "https://competition.francotech.gov.kh",
    featured: true
  },
  {
    id: 12,
    name: "Digital and Green Innovation - Youth Cohort (DGIy)",
    description: "A youth innovation program under the EU/GIZ-backed Digital and Green Innovation Action,delivered in Cambodia by D4D Hub and DICHI Academy. Teams tackle real Cambodian environmental challenges across three tracks - Urban Planning & Sustainable Cities, Waste/Pollution & Public Health, and Food Security & Sustainable Agriculture - building digital solutions with no coding required. Includes 10 masterclass sessions, hands-on idea to working app mentorship, and a regional trip to Southeast Asia.",
    category: "Tech",
    level: "University",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_12.jpg",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 13,
    name: "Cybersecurity Short Video Competition 2026",
    description: "A short video competition by the Ministry of Post and Telecommunications (MPTC) inviting students to create 30-60 second educational videos raising awareness on cybersecurity topics (e.g. social engineering, phishing, AI, cyberbullying, IoT). The top video will represent Cambodia at the ASEAN-Japan Cybersecurity Video Competition 2026.",
    category: "Tech",
    level: "Open to All",
    deadline: "2026-07-17",
    status: "Closed",
    image: "assets/images/image_13.jpg",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 14,
    name: "DYNAMIC Agripreneur Bootcamp 2026",
    description: "A bootcamp under the KOICA-funded DYNAMIC initiative (Developing Youth and Nurturing Agripreneurship for Market Impact and Community Growth), for youth in Battambang province who are outside the formal education system. Helps participants explore agricultural start-up opportunities and develop viable business ideas through hands-on, practice-focused sessions from July 30 to August 2, 2026.",
    category: "Business",
    level: "Out-of-School Youth",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_14.jpg",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 15,
    name: "GCIP Cambodia Advanced Accelerator Program - Cohort 2",
    description: "A UNIDO/GEF-backed advanced-stage accelerator for cleantech startups and SMEs in Cambodia, run by Techo Startup Center. Provides seed funding, a dedicated lead Entrepreneur-in-Residence (EIR), and a cross-border network to help ventures scale their cleantech solutions into global markets.",
    category: "Business",
    level: "Open to All",
    deadline: "2026-08-23",
    status: "Open",
    image: "assets/images/image_15.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 16,
    name: "Cambodia: Accelerating Actions to Improve Organic Waste Management",
    description: "A call for proposals from the Climate & Clean Air Coalition inviting eligible organizations to implement a $700,000 project supporting Cambodia's Ministry of Environment in reducing methane emissions through improved organic waste and wastewater management.",
    category: "Environment",
    level: "Open to All",
    deadline: "2026-08-14",
    status: "Open",
    image: "assets/images/image_16.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 17,
    name: "Innovate Cambodia Accelerator Program – Batch 3",
    description: "The third batch of Plug and Play Cambodia's accelerator program, run in partnership with the Ministry of Post and Telecommunications and the AUPP Technology Center. Supports emerging Cambodian startups across Financial Services, Food & Agriculture, Education, and Travel & Hospitality through mentorship, workshops, and access to Plug and Play's global network of corporates and investors.",
    category: "Business",
    level: "Open to All",
    deadline: "2026-08-21",
    status: "Open",
    image: "assets/images/image_17.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 18,
    name: "SparkMeet Season 5 – Women Innovator Bootcamp",
    description: "A 6-week in-person bootcamp under SparkMeet Season 5's Inclusive Program by Techo Startup Center, designed to support women in learning, growing, and exploring meaningful ideas through guided sessions, expert speakers, and team-based activities. Limited participants selected.",
    category: "Business",
    level: "Open to All",
    deadline: "2026-05-03",
    status: "Closed",
    image: "assets/images/image_18.jpg",
    registerLink: "https://...",
    featured: true
  }
];
