const competitions = [
  {
    id: 1,
    name: "NextGen Enterprise 2.0",
    description: "A business development program equipping MSMEs and entrepreneurs in agriculture, tourism, services, and FMCG sectors with skills to strengthen and grow their enterprises.",
    category: "Business",
    level: "University",
    deadline: "2026-08-14",
    status: "Open",
    image: "assets/images/image_1.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 2,
    name: "Clean Energy Awards 2026",
    description: "An award recognizing businesses, innovations, and initiatives driving Cambodia's clean energy transition, across the Clean Energy Champion, Energy Efficiency, and Cleantech Award categories.",
    category: "Environment",
    level: "Any Level",
    deadline: "2026-08-22",
    status: "Open",
    image: "assets/images/image_2.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 3,
    name: "KE Startup Awards 2026",
    description: "Khmer Enterprise's annual awards competition recognizing outstanding Cambodian startups, entrepreneurs, and SMEs for their innovative contributions to the country's entrepreneurial ecosystem.",
    category: "Business",
    level: "University",
    deadline: "2026-07-15",
    status: "Closed",
    image: "assets/images/image_3.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Khmer Enterprise (KE)"
  },
  {
    id: 4,
    name: "RISE Week 2026",
    description: "A capstone event celebrating young innovators from Tech for Kids Academy's flagship programs, featuring project showcases, a team pitching competition, industry talks, and an award ceremony.",
    category: "Tech",
    level: "High School",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_4.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Tech for Kids Academy"
  },
  {
    id: 5,
    name: "Reverse Innovation Cohort 6",
    description: "A 3-month accelerator program for startups to develop tech-based solutions to real market challenges presented by industry Challenge Owners, with mentorship from domain experts.",
    category: "Tech",
    level: "University",
    deadline: "2026-07-23",
    status: "Closed",
    image: "assets/images/image_5.jpg",
    registerLink: "https://airtable.com/appz0Cfn1uXVH.../pagMFJrW9MjkttSBQ/form",
    featured: true
  },
  {
    id: 6,
    name: "ASEAN Youth Speech Contest 2026",
    description: "A public speaking competition inviting ASEAN youth aged 16-25 to share their vision on the theme 'Navigating Our Future, Together.'",
    category: "Non-Tech",
    level: "University",
    deadline: "2026-07-03",
    status: "Closed",
    image: "assets/images/image_6.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 7,
    name: "Creator Marathon Open Competition",
    description: "An open content creation competition under the Mekong Tech Festival's 4th GenZ Mekong Tech 2026 event, themed Build, Compete, Connect, Scale.",
    category: "Design",
    level: "Any Level",
    deadline: "2026-09-25",
    status: "Open",
    image: "assets/images/image_7.jpg",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 8,
    name: "Highschool Club Entrepreneurs Program 2026",
    description: "A program by Khmer Enterprise for high school students to join an entrepreneurship club, building foundational business and startup skills.",
    category: "Business",
    level: "High School",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_8.jpg",
    registerLink: "https://...",
    featured: false,
    organizer: "Khmer Enterprise (KE)"
  },
  {
    id: 9,
    name: "Bridging the Cold Chain Gap Challenge",
    description: "A technology innovation challenge by ADB and the High-Level Technology Fund seeking affordable cold chain solutions to reduce post-harvest food loss for last-mile fruit and vegetable vendors in India.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-09-04",
    status: "Open",
    image: "assets/images/image_9.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Asian Development Bank (ADB) / High-Level Technology Fund",
    location: "India"
  },
  {
    id: 10,
    name: "Turing Hackathon Cycle 10",
    description: "A five-day, community-driven hackathon empowering youth to build digital solutions that drive innovation and cultivate entrepreneurship for Cambodia's next generation of founders. Held in Siem Reap this cycle.",
    category: "Tech",
    level: "University",
    deadline: "2026-06-14",
    status: "Closed",
    image: "assets/images/image_10.jpg",
    registerLink: "https://...",
    featured: true,
    location: "Siem Reap"
  },
  {
    id: 11,
    name: "FrancoTech Innovation Competition 2026",
    description: "An international competition organized by Cambodia's Ministry of Post and Telecommunications, held alongside the 20th Francophonie Summit in Phnom Penh, recognizing breakthrough digital innovations across Francophone nations.",
    about: "Held under the theme 'Digital Innovation Across Francophone Nations,' this competition is Cambodia's contribution to hosting the 20th Francophonie Summit, welcoming the 90 member states and governments of the International Organization of La Francophonie (OIF). It's co-organized by MPTC and the Ministry of Women's Affairs, supported by the CBRD Fund, and run in partnership with Metfone. Two award tracks — Best Digital Innovation and Best Women Technopreneurs — are open to startups, innovators, and digital solution providers across the Francophone ecosystem. Each track awards three teams (Gold/Silver/Bronze, valued at $3,000/$2,000/$1,000 with trophies), and every winning team also receives $2,000 in financial support to attend the Final Judging and Award Ceremony in Phnom Penh. Timeline: applications opened July 9, 2026, close September 1, semi-final judging runs online September 16, and the Final Judging & Award Ceremony takes place November 15 at Koh Pich Convention Center.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-09-01",
    status: "Open",
    image: "assets/images/image_11.jpg",
    registerLink: "https://competition.francotech.gov.kh",
    featured: true,
    organizer: "Ministry of Post and Telecommunications (MPTC), with Ministry of Women's Affairs",
    location: "Koh Pich Convention Center, Phnom Penh"
  },
  {
    id: 12,
    name: "Digital and Green Innovation - Youth Cohort (DGIy)",
    description: "A youth innovation program under the EU/GIZ-backed Digital and Green Innovation Action, delivered in Cambodia by D4D Hub and DICHI Academy, where teams build digital solutions to real Cambodian environmental challenges.",
    about: "Teams work across three tracks — Urban Planning & Sustainable Cities, Waste/Pollution & Public Health, and Food Security & Sustainable Agriculture — building digital solutions with no coding required. The program includes 10 masterclass sessions, hands-on mentorship taking ideas to working apps, and a regional trip to Southeast Asia for participating teams. It sits under the broader Digital and Green Innovation (DGI) Action, a Team Europe initiative co-funded by the EU, Germany's BMZ, and other European partners, active across Sub-Saharan Africa, Latin America and the Caribbean, and Asia-Pacific.",
    category: "Tech",
    level: "University",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_12.jpg",
    registerLink: "https://...",
    featured: false,
    organizer: "D4D Hub and DICHI Academy"
  },
  {
    id: 13,
    name: "Cybersecurity Short Video Competition 2026",
    description: "A short video competition by the Ministry of Post and Telecommunications (MPTC) inviting students to create 30-60 second educational videos raising awareness on cybersecurity topics.",
    about: "Open to students from lower-secondary school up, under 30 years old, with Khmer nationality. Entries must be 30-60 seconds, original work, publicly posted on both Facebook and TikTok, and include subtitles in the opposite language from the one spoken (Khmer videos need English subtitles and vice versa). Participants pick a topic from a set list — including social engineering scams, money mule fraud, AI, cyberbullying, QR code phishing, cyber safety for seniors, IoT, and smart devices — or another cybersecurity-related theme. Judging is 50% message clarity, 25% creativity, 25% technical quality. Three winners receive cash prizes (2,000,000 / 1,000,000 / 600,000 riel), and the top video will represent Cambodia at the ASEAN-Japan Cybersecurity Video Competition 2026. Results announced August 10, 2026.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-07-17",
    status: "Closed",
    image: "assets/images/image_13.jpg",
    registerLink: "https://...",
    featured: false,
    organizer: "Ministry of Post and Telecommunications (MPTC)",
    teamSize: "Individual"
  },
  {
    id: 14,
    name: "DYNAMIC Agripreneur Bootcamp 2026",
    description: "A bootcamp under the KOICA-funded DYNAMIC initiative, for youth in Battambang province who are outside the formal education system, helping them explore agricultural start-up opportunities.",
    about: "This Battambang track is run by Wonders, ChorogUsan for Children, and Phum Impact, funded by KOICA. It's part of the broader DYNAMIC project (Developing Youth and Nurturing Agripreneurship for Market Impact and Community Growth), a $2.45 million KOICA-funded initiative jointly implemented nationally by ChildFund Korea, Wonders International, the National Incubation Center of Cambodia, and the Royal University of Agriculture — which also runs related tracks like the DYNAMIC Agribusiness Builder program for university agriculture students. Participants develop viable business ideas through hands-on, practice-focused sessions running July 30 to August 2, 2026, in Battambang city.",
    category: "Business",
    level: "Out-of-School Youth",
    deadline: "2026-07-25",
    status: "Closed",
    image: "assets/images/image_14.jpg",
    registerLink: "https://...",
    featured: false,
    organizer: "Wonders, ChorogUsan for Children, and Phum Impact (funded by KOICA)",
    location: "Battambang"
  },
  {
    id: 15,
    name: "GCIP Cambodia Advanced Accelerator Program - Cohort 2",
    description: "A UNIDO/GEF-backed advanced-stage accelerator for cleantech startups and SMEs in Cambodia, run by Techo Startup Center.",
    about: "This is the advanced-stage phase of the Global Cleantech Innovation Programme (GCIP), a UNIDO initiative funded by the Global Environment Facility (GEF) that runs in 15+ countries worldwide with a total program budget over $27 million. In Cambodia, GCIP focuses on sectors including agriculture, hospitality, and manufacturing — with cleantech applications like renewable energy, energy efficiency, circular economy, green building, and green logistics. Support includes seed funding, a dedicated lead Entrepreneur-in-Residence (EIR), and a cross-border network to help ventures scale into global markets. Previous GCIP Cambodia cohorts have distributed grants totaling $50,000 across top finalist teams.",
    category: "Business",
    level: "Any Level",
    deadline: "2026-08-23",
    status: "Open",
    image: "assets/images/image_15.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Techo Startup Center (UNIDO / GEF-backed)"
  },
  {
    id: 16,
    name: "Cambodia: Accelerating Actions to Improve Organic Waste Management",
    description: "A call for proposals from the Climate & Clean Air Coalition inviting eligible organizations to implement a $700,000 project supporting Cambodia's Ministry of Environment in reducing methane emissions through improved organic waste and wastewater management.",
    category: "Environment",
    level: "Any Level",
    deadline: "2026-08-14",
    status: "Open",
    image: "assets/images/image_16.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Climate & Clean Air Coalition, with Cambodia's Ministry of Environment",
    location: "Phnom Penh, Siem Reap, Kampong Chhnang, and Koh Sralao Island (Koh Kong) — pilot locations"
  },
  {
    id: 17,
    name: "Innovate Cambodia Accelerator Program – Batch 3",
    description: "The third batch of Plug and Play Cambodia's accelerator program, run in partnership with the Ministry of Post and Telecommunications and the AUPP Technology Center.",
    about: "Plug and Play is a global innovation platform (founded 2006) with a presence in 30+ locations worldwide, whose portfolio companies have collectively raised over $9 billion in funding. In Cambodia, the program supports emerging startups across Financial Services, Food & Agriculture, Education, Travel & Hospitality, and Logistics through mentorship, workshops, and access to Plug and Play's global network of corporates and investors. Since Batch 1 launched in September 2025, the program has helped Cambodian startups attract real investment — including Bamnang (a student-focused housing and mentorship superapp) and konektAgri (an agricultural credit and risk-assessment platform), both of which received direct investment from Plug and Play.",
    category: "Business",
    level: "Any Level",
    deadline: "2026-08-21",
    status: "Open",
    image: "assets/images/image_17.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Plug and Play Cambodia, with MPTC and AUPP Technology Center"
  },
  {
    id: 18,
    name: "SparkMeet Season 5 – Women Innovator Bootcamp",
    description: "A 6-week in-person bootcamp under SparkMeet Season 5's Inclusive Program by Techo Startup Center, designed to support women in learning, growing, and exploring meaningful ideas.",
    about: "SparkMeet is an ongoing program series run by Techo Startup Center — this Women Innovator Bootcamp is part of Season 5's Inclusive Program track. Over 6 weeks of in-person sessions, participants take part in guided training, hear from expert speakers, and work through team-based activities together. Only a limited number of participants are selected.",
    category: "Business",
    level: "Any Level",
    deadline: "2026-05-03",
    status: "Closed",
    image: "assets/images/image_18.jpg",
    registerLink: "https://...",
    featured: true,
    organizer: "Techo Startup Center"
  }
];