const competitions = [
  {
    id: 1,
    name: "Google Solution Challenge",
    description: "Build solutions using Google technologies.",
    category: "Tech",
    level: "University",
    deadline: "2026-08-15",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 2,
    name: "National Business Case Cup",
    description: "Solve real business problems with a small team.",
    category: "Business",
    level: "University",
    deadline: "2026-08-22",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 3,
    name: "UI/UX Design Sprint",
    description: "Design a mobile app in 48 hours.",
    category: "Design",
    level: "Any Level",
    deadline: "2026-09-01",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: true
  },
  {
    id: 4,
    name: "Youth Science Fair 2026",
    description: "Present an original science project to expert judges.",
    category: "Science",
    level: "High School",
    deadline: "2026-09-10",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 5,
    name: "Reverse Innovation Cohort 6",
    description: "A 3-month accelerator program for startups to develop tech-based solutions to real market challenges presented by industry Challenge Owners, with mentorship from domain experts.",
    category: "Tech",
    level: "University",
    deadline: "2026-07-23",
    status: "Closed",
    image: "assets/images/image 5.png",
    registerLink: "https://airtable.com/appz0Cfn1uXVH.../pagMFJrW9MjkttSBQ/form",
    featured: true
  },
  {
    id: 6,
    name: "Startup Pitch Night",
    description: "Pitch your startup idea to a panel of investors.",
    category: "Business",
    level: "University",
    deadline: "2026-09-18",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 7,
    name: "Robotics Challenge Cambodia",
    description: "Build and program a robot to complete set tasks.",
    category: "Science",
    level: "High School",
    deadline: "2026-09-25",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 8,
    name: "Brand Identity Design Contest",
    description: "Create a full brand identity for a fictional company.",
    category: "Design",
    level: "University",
    deadline: "2026-10-01",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 9,
    name: "AI for Good Hackathon",
    description: "Use AI to tackle a social or environmental issue.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-10-05",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 10,
    name: "Youth to Business Hackathon 2026",
    description: "Bridge student ideas with real business mentorship.",
    category: "Business",
    level: "University",
    deadline: "2026-10-12",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 11,
    name: "MIT Hack for Social Impact",
    description: "Build tech solutions for underserved communities.",
    category: "Tech",
    level: "University",
    deadline: "2026-10-20",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 12,
    name: "ACTSmart Startup Program",
    description: "An accelerator-style program for early-stage founders.",
    category: "Business",
    level: "Any Level",
    deadline: "2026-11-02",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 13,
    name: "Environmental Science Olympiad",
    description: "Compete in an environmental science knowledge challenge.",
    category: "Science",
    level: "High School",
    deadline: "2026-11-08",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 14,
    name: "Poster Design Challenge",
    description: "Design a poster around this year's chosen theme.",
    category: "Design",
    level: "High School",
    deadline: "2026-11-15",
    status: "Closed",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 15,
    name: "Community Coding Bootcamp Demo Day",
    description: "Show off a project built during the coding bootcamp.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-11-20",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 16,
    name: "Finance Case Competition",
    description: "Analyze a real financial case and present recommendations.",
    category: "Business",
    level: "University",
    deadline: "2026-11-28",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 17,
    name: "Game Jam Cambodia",
    description: "Build a playable game from scratch in one weekend.",
    category: "Tech",
    level: "Any Level",
    deadline: "2026-12-05",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  },
  {
    id: 18,
    name: "Open Innovation Challenge",
    description: "Tackle an open-ended problem statement your own way.",
    category: "Other",
    level: "Any Level",
    deadline: "2026-12-12",
    status: "Open",
    image: "https://placehold.co/600x350",
    registerLink: "https://...",
    featured: false
  }
];
